-- MySQL Script generated by MySQL Workbench
-- Sat Oct 22 17:54:13 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utama`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utama` (
  `Nomor_peserta` INT NULL,
  `Nomor_keluarga` INT NULL,
  `Bobot` FLOAT NULL,
  `ID_Kunjungan_FKTP` VARCHAR(45) NULL,
  `Tanggal_datang_kunjungan_FKTP` DATE NULL,
  `Tanggal_pulang_kunjungan_FKTP` DATE NULL,
  `Provinsi_FKTP` INT NULL,
  `Kabupaten_Kota_FKTP` INT NULL,
  `Kepemilikan_FKTP` INT NULL,
  `Jenis_FKTP` INT NULL,
  `Tipe_FKTP` INT NULL,
  `Tingkat_Pelayanan_FKTP` INT NULL,
  `Jenis_Poli_FKTP` INT NULL,
  `Segmen_Peserta_FKTP` INT NULL,
  `Kode_diagnosis_ICD_10` INT NULL,
  `Kode_diagnosis` INT NULL,
  `Nama_diagnosis` INT NULL,
  `Provinsi_faskes_tujuan_rujukan` INT NULL,
  `Kabupaten_Kota_faskes_tujuan_rujukan` INT NULL,
  `Jenis_faskes_tujuan_rujukan` INT NULL,
  `Tipe_faskes_tujuan_rujukan` INT NULL,
  `Poli_faskes_tujuan_rujukan` INT NULL,
  `Jenis_Kunjungan_FKTP` INT NULL,
  `Kelas_Status_Pulang_Peserta` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipe_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipe_FKTP` (
  `id_Tipe_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Tipe_FKTP` INT NULL,
  `label_Provinsi_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Tipe_FKTP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jenis_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jenis_FKTP` (
  `id_Jenis_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Jenis_FKTP` INT NULL,
  `label_Jenis_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Jenis_FKTP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provinsi_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provinsi_FKTP` (
  `id_Provinsi_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Provinsi_FKTP` INT NULL,
  `label_Provinsi_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Provinsi_FKTP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tingkat_Pelayanan_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tingkat_Pelayanan_FKTP` (
  `id_Tingkat_Pelayanan_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Tingkat_Pelayanan_FKTP` INT NULL,
  `label_Tingkat_Pelayanan_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Tingkat_Pelayanan_FKTP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jenis_Poli_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jenis_Poli_FKTP` (
  `id_Jenis_Poli_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Jenis_Poli_FKTP` INT NULL,
  `label_Jenis_Poli_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Jenis_Poli_FKTP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Segmen_Peserta_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Segmen_Peserta_FKTP` (
  `id_Segmen_Peserta_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Segmen_Peserta_FKTP` INT NULL,
  `label_Segmen_Peserta_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Segmen_Peserta_FKTP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kepemilikan_faskes_tujuan_rujukan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (
  `id_Kepemilikan_faskes_tujuan_rujukan` INT NOT NULL AUTO_INCREMENT,
  `nomor_Kepemilikan_faskes_tujuan_rujukan` INT NULL,
  `label_Kepemilikan_faskes_tujuan_rujukan` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Kepemilikan_faskes_tujuan_rujukan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jenis_faskes_tujuan_rujukan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jenis_faskes_tujuan_rujukan` (
  `id_Jenis_faskes_tujuan_rujukan` INT NOT NULL AUTO_INCREMENT,
  `nomor_Jenis_faskes_tujuan_rujukan` INT NULL,
  `label_Jenis_faskes_tujuan_rujukan` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Jenis_faskes_tujuan_rujukan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipe_faskes_tujuan_rujukan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipe_faskes_tujuan_rujukan` (
  `id_Tipe_faskes_tujuan_rujukan` INT NOT NULL AUTO_INCREMENT,
  `nomor_Tipe_faskes_tujuan_rujukan` INT NULL,
  `label_Tipe_faskes_tujuan_rujukan` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Tipe_faskes_tujuan_rujukan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jenis_Kunjungan_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jenis_Kunjungan_FKTP` (
  `id_Jenis_Kunjungan_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Jenis_Kunjungan_FKTP` INT NULL,
  `label_Jenis_Kunjungan_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Jenis_Kunjungan_FKTP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Poli_faskes_tujuan_rujukan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Poli_faskes_tujuan_rujukan` (
  `id_Poli_faskes_tujuan_rujukan` INT NOT NULL AUTO_INCREMENT,
  `nomor_Poli_faskes_tujuan_rujukan` INT NULL,
  `label_Poli_faskes_tujuan_rujukan` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Poli_faskes_tujuan_rujukan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kelas_Status_Pulang_Peserta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kelas_Status_Pulang_Peserta` (
  `id_Kelas_Status_Pulang_Peserta` INT NOT NULL AUTO_INCREMENT,
  `label_Kelas_Status_Pulang_Peserta` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Kelas_Status_Pulang_Peserta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provinsi_faskes_tujuan_rujukan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provinsi_faskes_tujuan_rujukan` (
  `id_Provinsi_faskes_tujuan_rujukan` INT NOT NULL AUTO_INCREMENT,
  `nomor_Provinsi_faskes_tujuan_rujukan` INT NULL,
  `label_Provinsi_faskes_tujuan_rujukan` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Provinsi_faskes_tujuan_rujukan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Kepemilikan_FKTP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Kepemilikan_FKTP` (
  `id_Kepemilikan_FKTP` INT NOT NULL AUTO_INCREMENT,
  `nomor_Kepemilikan_FKTP` INT NULL,
  `label_Jenis_FKTP` VARCHAR(50) NULL,
  PRIMARY KEY (`id_Kepemilikan_FKTP`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`Tipe_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (1, 1, 'Klinik Non Rawat Inap');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (2, 2, 'Dokter Prakter Perorangan');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (3, 3, 'Non Rawat Inap');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (4, 4, 'Rawat Inap');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (5, 5, 'Klinik Rawat Inap');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (6, 6, 'Dokter Gigi');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (7, 7, 'RS Kelas D Pratama');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (8, 8, 'Laboratorium');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (9, 9, 'Faskes IVA/Pap Smear');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (10, 10, 'PPK Lain-lain');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (11, 11, 'Klaim Khusus');
INSERT INTO `mydb`.`Tipe_FKTP` (`id_Tipe_FKTP`, `nomor_Tipe_FKTP`, `label_Provinsi_FKTP`) VALUES (12, 12, 'Faskes DBTFMSÃ‚Â ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Jenis_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Jenis_FKTP` (`id_Jenis_FKTP`, `nomor_Jenis_FKTP`, `label_Jenis_FKTP`) VALUES (1, 1, 'Puskesmas');
INSERT INTO `mydb`.`Jenis_FKTP` (`id_Jenis_FKTP`, `nomor_Jenis_FKTP`, `label_Jenis_FKTP`) VALUES (2, 2, 'Klinik Pratama');
INSERT INTO `mydb`.`Jenis_FKTP` (`id_Jenis_FKTP`, `nomor_Jenis_FKTP`, `label_Jenis_FKTP`) VALUES (3, 3, 'Dokter Umum');
INSERT INTO `mydb`.`Jenis_FKTP` (`id_Jenis_FKTP`, `nomor_Jenis_FKTP`, `label_Jenis_FKTP`) VALUES (4, 4, 'Dokter gigi');
INSERT INTO `mydb`.`Jenis_FKTP` (`id_Jenis_FKTP`, `nomor_Jenis_FKTP`, `label_Jenis_FKTP`) VALUES (5, 5, 'Laboratorium');
INSERT INTO `mydb`.`Jenis_FKTP` (`id_Jenis_FKTP`, `nomor_Jenis_FKTP`, `label_Jenis_FKTP`) VALUES (6, 6, 'Lain-lain');
INSERT INTO `mydb`.`Jenis_FKTP` (`id_Jenis_FKTP`, `nomor_Jenis_FKTP`, `label_Jenis_FKTP`) VALUES (7, 7, 'JejaringÂ ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Provinsi_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (1, 11, 'Aceh');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (2, 12, 'Sumatera Utara');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (3, 13, 'Sumatera Barat');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (4, 14, 'Riau');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (5, 15, 'Jambi');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (6, 16, 'Sumatera Selatan');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (7, 17, 'Bengkulu');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (8, 18, 'Lampung');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (9, 19, 'Kepulauan Bangka Belitung');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (10, 21, 'Kepulauan Riau');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (11, 31, 'DKI Jakarta');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (12, 32, 'Jawa Barat');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (13, 33, 'Jawa Tengah');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (14, 34, 'DI Yogyakarta');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (15, 35, 'Jawa Timur');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (16, 36, 'Banten');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (17, 51, 'Bali');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (18, 52, 'Nusa Tenggara Barat');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (19, 53, 'Nusa Tenggara Timur');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (20, 61, 'Kalimantan Barat');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (21, 62, 'Kalimantan Tengah');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (22, 63, 'Kalimantan Selatan');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (23, 64, 'Kalimantan Timur');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (24, 65, 'Kalimantan Utara');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (25, 71, 'Sulawesi Utara');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (26, 72, 'Sulawesi Tengah');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (27, 73, 'Sulawesi Selatan');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (28, 74, 'Sulawesi Tenggara');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (29, 75, 'Gorontalo');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (30, 76, 'Sulawesi Barat');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (31, 81, 'Maluku');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (32, 82, 'Maluku Utara');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (33, 91, 'Papua Barat');
INSERT INTO `mydb`.`Provinsi_FKTP` (`id_Provinsi_FKTP`, `nomor_Provinsi_FKTP`, `label_Provinsi_FKTP`) VALUES (34, 94, 'Papua');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Tingkat_Pelayanan_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Tingkat_Pelayanan_FKTP` (`id_Tingkat_Pelayanan_FKTP`, `nomor_Tingkat_Pelayanan_FKTP`, `label_Tingkat_Pelayanan_FKTP`) VALUES (1, 1, 'RJTP');
INSERT INTO `mydb`.`Tingkat_Pelayanan_FKTP` (`id_Tingkat_Pelayanan_FKTP`, `nomor_Tingkat_Pelayanan_FKTP`, `label_Tingkat_Pelayanan_FKTP`) VALUES (2, 2, 'RITP');
INSERT INTO `mydb`.`Tingkat_Pelayanan_FKTP` (`id_Tingkat_Pelayanan_FKTP`, `nomor_Tingkat_Pelayanan_FKTP`, `label_Tingkat_Pelayanan_FKTP`) VALUES (3, 3, 'Promotif');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Jenis_Poli_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (1, 1, 'POLI UMUM');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (2, 2, 'POLI GIGI & MULUT');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (3, 3, 'POLI KIA');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (4, 4, 'UGD');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (5, 5, 'POLI KB');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (6, 6, 'POLI PERSALINAN');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (7, 7, 'LABORATORIUM');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (8, 8, 'Penyakit Dalam');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (9, 9, 'POLI REFRAKSI');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (10, 10, 'Fisio');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (11, 11, 'Imunisasi');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (12, 12, 'Home-Visit');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (13, 13, 'Konseling');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (14, 14, 'POLI LANSIA');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (15, 15, 'Umum Anak');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (16, 16, 'Telp/SMS');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (17, 17, 'Imunisasi (BCG)');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (18, 18, 'Imunisasi (DPT)');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (19, 19, 'Imunisasi (Polio)');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (20, 20, 'Imunisasi (Campak)');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (21, 21, 'Imunisasi (Hep B)');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (22, 22, 'POLI DIABETES');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (23, 23, 'POLI GIZI');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (24, 24, 'POLI HIV & IMS');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (25, 25, 'POLI JIWA');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (26, 26, 'POLI KUSTA');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (27, 27, 'POLI TB & PARU');
INSERT INTO `mydb`.`Jenis_Poli_FKTP` (`id_Jenis_Poli_FKTP`, `nomor_Jenis_Poli_FKTP`, `label_Jenis_Poli_FKTP`) VALUES (28, 28, 'KUNJUNGAN ONLINE');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Segmen_Peserta_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Segmen_Peserta_FKTP` (`id_Segmen_Peserta_FKTP`, `nomor_Segmen_Peserta_FKTP`, `label_Segmen_Peserta_FKTP`) VALUES (1, 1, 'Bukan pekerja');
INSERT INTO `mydb`.`Segmen_Peserta_FKTP` (`id_Segmen_Peserta_FKTP`, `nomor_Segmen_Peserta_FKTP`, `label_Segmen_Peserta_FKTP`) VALUES (2, 2, 'PBI APBN');
INSERT INTO `mydb`.`Segmen_Peserta_FKTP` (`id_Segmen_Peserta_FKTP`, `nomor_Segmen_Peserta_FKTP`, `label_Segmen_Peserta_FKTP`) VALUES (3, 3, 'PBI APBD');
INSERT INTO `mydb`.`Segmen_Peserta_FKTP` (`id_Segmen_Peserta_FKTP`, `nomor_Segmen_Peserta_FKTP`, `label_Segmen_Peserta_FKTP`) VALUES (4, 4, 'PBPU');
INSERT INTO `mydb`.`Segmen_Peserta_FKTP` (`id_Segmen_Peserta_FKTP`, `nomor_Segmen_Peserta_FKTP`, `label_Segmen_Peserta_FKTP`) VALUES (5, 5, 'PPUÃ‚Â ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Kepemilikan_faskes_tujuan_rujukan`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (1, 1, 'Vertikal/pusat');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (2, 2, 'Pemerintah provinsi');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (3, 3, 'Pemerintah kabupaten/kota');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (4, 4, 'Polri');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (5, 5, 'TNI AD');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (6, 6, 'TNI AL');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (7, 7, 'TNI AU');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (8, 8, 'BUMN');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (9, 9, 'Swasta');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (10, 98, 'Tidak dirujuk');
INSERT INTO `mydb`.`Kepemilikan_faskes_tujuan_rujukan` (`id_Kepemilikan_faskes_tujuan_rujukan`, `nomor_Kepemilikan_faskes_tujuan_rujukan`, `label_Kepemilikan_faskes_tujuan_rujukan`) VALUES (11, 99, 'MissingÃ‚Â ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Jenis_faskes_tujuan_rujukan`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Jenis_faskes_tujuan_rujukan` (`id_Jenis_faskes_tujuan_rujukan`, `nomor_Jenis_faskes_tujuan_rujukan`, `label_Jenis_faskes_tujuan_rujukan`) VALUES (1, 1, 'Puskesmas');
INSERT INTO `mydb`.`Jenis_faskes_tujuan_rujukan` (`id_Jenis_faskes_tujuan_rujukan`, `nomor_Jenis_faskes_tujuan_rujukan`, `label_Jenis_faskes_tujuan_rujukan`) VALUES (2, 2, 'Klinik Pratama');
INSERT INTO `mydb`.`Jenis_faskes_tujuan_rujukan` (`id_Jenis_faskes_tujuan_rujukan`, `nomor_Jenis_faskes_tujuan_rujukan`, `label_Jenis_faskes_tujuan_rujukan`) VALUES (3, 3, 'Dokter Umum');
INSERT INTO `mydb`.`Jenis_faskes_tujuan_rujukan` (`id_Jenis_faskes_tujuan_rujukan`, `nomor_Jenis_faskes_tujuan_rujukan`, `label_Jenis_faskes_tujuan_rujukan`) VALUES (4, 98, 'Tidak dirujuk');
INSERT INTO `mydb`.`Jenis_faskes_tujuan_rujukan` (`id_Jenis_faskes_tujuan_rujukan`, `nomor_Jenis_faskes_tujuan_rujukan`, `label_Jenis_faskes_tujuan_rujukan`) VALUES (5, 99, 'MissingÃ‚Â ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Tipe_faskes_tujuan_rujukan`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (1, 1, 'Apotik Kronis');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (2, 2, 'Apotik PRB dan Kronis');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (3, 3, 'Dokter Gigi');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (4, 4, 'Dokter Prakter Perorangan');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (5, 5, 'Khusus Bedah');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (6, 6, 'Khusus Gigi dan Mulut');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (7, 7, 'Khusus Hemodialisa');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (8, 8, 'Khusus Ibu dan Anak');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (9, 9, 'Khusus Jantung');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (10, 10, 'Khusus Jiwa');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (11, 11, 'Khusus Kanker (Onkologi)');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (12, 12, 'Khusus Kusta');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (13, 13, 'Khusus Lain');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (14, 14, 'Khusus Mata');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (15, 15, 'Khusus Paru');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (16, 16, 'Khusus Stroke');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (17, 17, 'Khusus Tulang');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (18, 18, 'Klinik Non Rawat Inap');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (19, 19, 'Laboratorium');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (20, 21, 'Non Rawat Inap');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (21, 22, 'Optik');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (22, 24, 'Rawat Inap');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (23, 25, 'RS CoB');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (24, 26, 'RS Kelas A');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (25, 27, 'RS Kelas B');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (26, 28, 'RS Kelas C');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (27, 29, 'RS Kelas D');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (28, 30, 'RS Kelas D Pratama');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (29, 31, 'RS Non Provider (GawatDarurat)');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (30, 32, 'RS Swasta Setara Type A');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (31, 33, 'RS Swasta Setara Type B');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (32, 34, 'RS Swasta Setara Type C');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (33, 35, 'RS Swasta Setara Type D');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (34, 36, 'RS TNI Polri Kelas I');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (35, 37, 'RS TNI Polri Kelas II');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (36, 38, 'RS TNI Polri Kelas III');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (37, 39, 'RS TNI Polri Kelas IV');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (38, 40, 'Faskes IVA/Pap Smear');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (39, 41, 'Klinik Rawat Inap');
INSERT INTO `mydb`.`Tipe_faskes_tujuan_rujukan` (`id_Tipe_faskes_tujuan_rujukan`, `nomor_Tipe_faskes_tujuan_rujukan`, `label_Tipe_faskes_tujuan_rujukan`) VALUES (40, 42, 'PPK Tidak ditunjukÃ‚Â ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Jenis_Kunjungan_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Jenis_Kunjungan_FKTP` (`id_Jenis_Kunjungan_FKTP`, `nomor_Jenis_Kunjungan_FKTP`, `label_Jenis_Kunjungan_FKTP`) VALUES (1, 1, 'Kunjungan sakit');
INSERT INTO `mydb`.`Jenis_Kunjungan_FKTP` (`id_Jenis_Kunjungan_FKTP`, `nomor_Jenis_Kunjungan_FKTP`, `label_Jenis_Kunjungan_FKTP`) VALUES (2, 2, 'Kunjungan sehatÂ ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Poli_faskes_tujuan_rujukan`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (1, 1, 'Apotik Kronis');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (2, 2, 'Apotik PRB dan Kronis');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (3, 3, 'Dokter Gigi');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (4, 4, 'Dokter Prakter Perorangan');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (5, 5, 'Khusus Bedah');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (6, 6, 'Khusus Gigi dan Mulut');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (7, 7, 'Khusus Hemodialisa');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (8, 8, 'Khusus Ibu dan Anak');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (9, 9, 'Khusus Jantung');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (10, 10, 'Khusus Jiwa');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (11, 11, 'Khusus Kanker (Onkologi)');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (12, 12, 'Khusus Kusta');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (13, 13, 'Khusus Lain');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (14, 14, 'Khusus Mata');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (15, 15, 'Khusus Paru');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (16, 16, 'Khusus Stroke');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (17, 17, 'Khusus Tulang');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (18, 18, 'Klinik Non Rawat Inap');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (19, 19, 'Laboratorium');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (20, 21, 'Non Rawat Inap');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (21, 22, 'Optik');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (22, 24, 'Rawat Inap');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (23, 25, 'RS CoB');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (24, 26, 'RS Kelas A');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (25, 27, 'RS Kelas B');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (26, 28, 'RS Kelas C');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (27, 29, 'RS Kelas D');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (28, 30, 'RS Kelas D Pratama');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (29, 31, 'RS Non Provider (GawatDarurat)');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (30, 32, 'RS Swasta Setara Type A');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (31, 33, 'RS Swasta Setara Type B');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (32, 34, 'RS Swasta Setara Type C');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (33, 35, 'RS Swasta Setara Type D');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (34, 36, 'RS TNI Polri Kelas I');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (35, 37, 'RS TNI Polri Kelas II');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (36, 38, 'RS TNI Polri Kelas III');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (37, 39, 'RS TNI Polri Kelas IV');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (38, 40, 'Faskes IVA/Pap Smear');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (39, 41, 'Klinik Rawat Inap');
INSERT INTO `mydb`.`Poli_faskes_tujuan_rujukan` (`id_Poli_faskes_tujuan_rujukan`, `nomor_Poli_faskes_tujuan_rujukan`, `label_Poli_faskes_tujuan_rujukan`) VALUES (40, 42, 'PPK Tidak ditunjukÃ‚Â ');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Kelas_Status_Pulang_Peserta`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Kelas_Status_Pulang_Peserta` (`id_Kelas_Status_Pulang_Peserta`, `label_Kelas_Status_Pulang_Peserta`) VALUES (1, 'Sehat');
INSERT INTO `mydb`.`Kelas_Status_Pulang_Peserta` (`id_Kelas_Status_Pulang_Peserta`, `label_Kelas_Status_Pulang_Peserta`) VALUES (2, 'Belum_Sehat');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Provinsi_faskes_tujuan_rujukan`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (1, 11, 'Aceh');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (2, 12, 'Sumatera Utara');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (3, 13, 'Sumatera Barat');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (4, 14, 'Riau');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (5, 15, 'Jambi');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (6, 16, 'Sumatera Selatan');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (7, 17, 'Bengkulu');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (8, 18, 'Lampung');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (9, 19, 'Kepulauan Bangka Belitung');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (10, 21, 'Kepulauan Riau');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (11, 31, 'DKI Jakarta');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (12, 32, 'Jawa Barat');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (13, 33, 'Jawa Tengah');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (14, 34, 'DI Yogyakarta');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (15, 35, 'Jawa Timur');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (16, 36, 'Banten');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (17, 51, 'Bali');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (18, 52, 'Nusa Tenggara Barat');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (19, 53, 'Nusa Tenggara Timur');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (20, 61, 'Kalimantan Barat');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (21, 62, 'Kalimantan Tengah');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (22, 63, 'Kalimantan Selatan');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (23, 64, 'Kalimantan Timur');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (24, 65, 'Kalimantan Utara');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (25, 71, 'Sulawesi Utara');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (26, 72, 'Sulawesi Tengah');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (27, 73, 'Sulawesi Selatan');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (28, 74, 'Sulawesi Tenggara');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (29, 75, 'Gorontalo');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (30, 76, 'Sulawesi Barat');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (31, 81, 'Maluku');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (32, 82, 'Maluku Utara');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (33, 91, 'Papua Barat');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (34, 94, 'Papua');
INSERT INTO `mydb`.`Provinsi_faskes_tujuan_rujukan` (`id_Provinsi_faskes_tujuan_rujukan`, `nomor_Provinsi_faskes_tujuan_rujukan`, `label_Provinsi_faskes_tujuan_rujukan`) VALUES (35, 99, 'Tidak dilakukan rujukan');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Kepemilikan_FKTP`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (1, 1, 'Vertikal');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (2, 2, 'PemProv');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (3, 3, 'PemKab');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (4, 4, 'POLRI');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (5, 5, 'TNI AD');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (6, 6, 'TNI AL');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (7, 7, 'TNI AU');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (8, 8, 'BUMN');
INSERT INTO `mydb`.`Kepemilikan_FKTP` (`id_Kepemilikan_FKTP`, `nomor_Kepemilikan_FKTP`, `label_Jenis_FKTP`) VALUES (9, 9, 'SwastaÃ‚Â ');

COMMIT;

